### ISSUE TITLE
issue with set_trigger_out function 

### ISSUE THREAD

**Issue by Forest-Speed** [QI2lab/mcSIM#2] opened 2023-05-31 00:04 UTC
Hey, 

I am having an issue with the "set_trigger_out" in dlp6500.py. 

On line 1188 (for me),  "data = trig_byte + rising_edge_bytes + falling_edge_bytes" is leading to a type error. I have attached a screenshot below.

Thank You, 
Forest 

<img width="530" alt="Screen Shot 2023-05-30 at 5 55 31 PM" src="https://github.com/QI2lab/mcSIM/assets/89167253/a4538597-b040-4459-b719-7fc1cb9e9119">

**Comment by ptbrown1729** [comment] 2023-05-31 20:42
@Forest-Speed thanks for the bug report! Can you post the code you ran that generated this error? Or, better yet, a minimal example to reproduce the error

Please also include the version/branch of the repo you are using and the version of Python

**Comment by ptbrown1729** [comment] 2023-05-31 21:37
Looks like a simple issue where some of the items being added were lists and some were tuples. Should be fixed now  per [https://github.com/QI2lab/mcSIM/pull/3](https://github.com/QI2lab/mcSIM/pull/3)

Let me know if that works for you. FYI I have never had to use this function, so you will have to test if it correctly controls the DMD output trigger. If you have any problems feel free to post another issue here

**Comment by dpshepherd** [comment] 2023-06-09 17:08
@Forest-Speed - did Peter's change fix your issue?

**Comment by Forest-Speed** [comment] 2023-06-19 21:57
@dpshepherd - Hey Doug, I just responded to an email from Peter but wanted to post here as well. We had to take the DMD down to try some experiments with more LED power at the sample. I won't be able to test this until we have it back up. This may be a while, but I will let you both know ASAP. Thank you both for helping out so much!

**Comment by Forest-Speed** [comment] 2023-07-31 18:32
Working great! Thank you Peter.

**Closed as completed** 2023-07-31 19:00 UTC
Labels: bug
