### ISSUE TITLE
Error notification of the DMD simulation code

### ISSUE THREAD

**Issue by ranranking** [QI2lab/mcSIM#1] opened 2021-01-12 14:26 UTC
Hallo,
Firstly, thanks for providing the code for all!
I have downloaded the code and wanna to try to do some simulation with your code. But when i tried the example first, it came with a error notification and it cant go through the code. Could you have a look of the error and find where is the problem?

```
C:\Users\wanghaoran\Desktop\SIM_simulation\mcSIM-master\mcsim\simulate_dmd.py:582: RuntimeWarning: invalid value encountered in sqrt
  bz = -np.sqrt(1 - bx**2 - by**2)
Traceback (most recent call last):

  File "C:\Users\wanghaoran\Desktop\SIM_simulation\mcSIM-master\mcsim\simulate_dmd.py", line 1586, in <module>
    tout_offsets=np.linspace(-25, 25, 150) * np.pi / 180)

  File "C:\Users\wanghaoran\Desktop\SIM_simulation\mcSIM-master\mcsim\simulate_dmd.py", line 1146, in simulate_2d
    zip(tx_out[ii, jj].ravel(), ty_out[ii, jj].ravel())

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]

  File "C:\Users\wanghaoran\.conda\envs\tfcpu2\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]

  File "C:\Users\wanghaoran\Desktop\SIM_simulation\mcSIM-master\mcsim\simulate_dmd.py", line 122, in simulate_dmd
    phases = phase_fn(mxmx, mymy, amb[0], amb[1])

IndexError: index 1 is out of bounds for axis 0 with size 1
```

Thanks for your supporting!

**Comment by dpshepherd** [comment] 2021-01-12 20:39
@ptbrown1729, can you please take a look?

thanks!

**Comment by ptbrown1729** [comment] 2021-01-12 21:13
@ranranking sorry for the difficulties and thank you for pointing this out. I reproduced your issue on my system, and I pushed my latest version of simulate_dmd.py. That seems to resolve the problem. There was a minor inconsistency in the way some functions returned the unit vector difference amb. Please let me know if that resolved the issue for you.

Please let me know if you run into any other bugs, or have other comments on how we can improve this code.

**Comment by ranranking** [comment] 2021-01-12 21:16
Hallo Peter, thank you for the quick solution! I will try the new version tomorrow!

**Comment by ranranking** [comment] 2021-01-19 17:59
Hey Peter, i got another issue with the code.
```
simulate_2d_angles(wavelengths, gamma, dx, dy, tx_ins, ty_ins)
__main__:577: RuntimeWarning: invalid value encountered in sqrt
Traceback (most recent call last):

  File "<ipython-input-63-c8574070d14c>", line 1, in <module>
    simulate_2d_angles(wavelengths, gamma, dx, dy, tx_ins, ty_ins)

  File "<ipython-input-62-76d1689af0df>", line 1437, in simulate_2d_angles
    order=(nxs[aa, bb], nys[aa, bb]))

IndexError: too many indices for array
```

I am trying to use the simulate angles and i didnt get the point what is the problem.

Looking forward to solve it
Thanks

**Comment by ptbrown1729** [comment] 2021-01-19 18:44
@ranranking I am working on the fix for simulate_2d_angles().

Did running simulate_dmd.py as a script work for you after the last push?

I added two new example files under the folder "examples". Are you able to run these successfully?

**Comment by ptbrown1729** [comment] 2021-01-19 19:12
@ranranking I've corrected this bug. simulate_2d_angles() was a test function that I have not been using recently. For a usage example, see the script examples/dmd_find_nearest_diffraction_orders.py

Please let me know if this fixed your problem. Thanks again for pointing these bugs out!

**Comment by ranranking** [comment] 2021-01-19 20:15
Hi Peter, thanks for the reply again! The last bug with simulate_dmd works after your debug. I will try as your suggestion tomorrow, thank you

**Comment by ptbrown1729** [comment] 2021-01-22 22:24
Closing this because we have addressed these issues. Feel free to open another issue if you come across more bugs

**Closed as completed by ptbrown1729** 2021-01-22 22:24 UTC
Labels: bug
